name: "ci"
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install --no-interaction
      - name: check linting
        run: poetry run ruff check
      - name: check formatting
        run: poetry run ruff format --check
      - name: check types
        run: poetry run pyright
